numero = int(input("Insira um número para mostrar a tabuada: "))

a = (numero * 1)
b = (numero * 2)
c = (numero * 3)
d = (numero * 4)
e = (numero * 5) 
f = (numero * 6)
g = (numero * 7)
h = (numero * 8)
i = (numero * 9)
j = (numero * 10)

print(f"Tabuada do {numero}:")
print("-" * 12)
print(f"{numero} x 1 = {a}")
print(f"{numero} x 2 = {b}")
print(f"{numero} x 3 = {c}")
print(f"{numero} x 4 = {d}")
print(f"{numero} x 5 = {e}")
print(f"{numero} x 6 = {f}")
print(f"{numero} x 7 = {g}")
print(f"{numero} x 8 = {h}")
print(f"{numero} x 9 = {i}")
print(f"{numero} x 10 = {j}")
print("-" * 12)